before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: B0wqSaoGEKRrbOdLCdLfmDVtllWX88TFAxju+9FYTlfClWKR3Y9U6+FOeWvElSg71E1ELrQacqJu7iVpbsmsYSYZ0xAwls5CkYUIQWKrR2zEKxvfIHCmXLQy+2CGCwFdihQ5trC9RlUJHc6f3he7XmgnfsSSRqsOGTlz6Bneqbr0JMO5JBbicHhX6Fy4AoRbjsr3Il7P3l0B6M5lI9uZt6da6s79tMziL9u/r+6wil4koDGskx8C29RAuRkx8aeSSGI1Wl2uv7ig35ILL25QUa56PVgokbM6F2o0JWgXfDqRst5KIDgZZkPAnTDugVOBCVQ2IHWxPziMbWWMnZcdtFjRsIg3sYcRmTkwsU5+VcJR0SKNS3dE0VOAORNWotRxb92FVJ51v7QjGOn9RRbts6sZalzyUOASSU0JxNmdbPJfsUGq9vE3Akc8ZYM6Y5qR8ZuYoCDD//ObG8uz3krHROaxn1LS88FgPGf5W3+ii4JkPUQaMaZdVt4xaJqpXMxWSiO8ZC/meK+UZEgRNG9C6EEOO9KZzVAL5qRs2a8kX/Ao5h/q28f2a0zS2sVWo+AmEkQF/8XK5LhbUGtMrho50CfdpApFn27MCJg8zto6bQWR4K2rkxukjWZgCwyS90emGbck4BByu2VJ46/cVDfFCS4sXZdk798GdqlBtPcjrno= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
